### ISSUE TITLE
[DOCS-218] Feedback on "Managing branches"

### ISSUE THREAD

**Issue by bernd-wechner** [codacy/docs#498]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

Nice page. Was easy to find, and I was looking for how to enable analysis on my commits to the develop branch not just (or even in place of) master. And I found it here. Nice. Alas my Settings page does not have a Branches tab. OK. I can guess that's due to my plan (open source and free) and so you don't offer that, fine I guess, though a shame, I mean open source is open source and no-one really commits regularly to master, in my experience, much rather on development branches merging into master when a feature is finished. And to be honest I enable codacy a long time ago and totally forgot until I accidentally found myself working on master and pushing a commit and I got a codacy email. Like wow, it was nice. Thanks. I appreciate the feedback. Don't need it, it's open source and I slave at it like so many open source contributors with no reward other than the utility it provides me with (i..e not monetised in any way), but appreciate it, and thank you for it. But wonder if a) you'd if this help to explain why I don't see a Branches tab explicitly rather than leaving me to guess and/or b) providing it tot he open source license for reasons noted above. Master branch commits are a little late for feedback and I don't seem to get it anyhow when I push merges to master ...

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories-configure/managing-branches/

**Comment by pauloribeiro-codacy** [comment]
Hello @bernd-wechner,

The branches feature is available for open source accounts, so there must be something wrong with the Codacy access to your repository. You should be able to fix this by following these steps:

1. Sign out of Codacy.

    ![image](https://user-images.githubusercontent.com/60105800/109158707-a2b66300-776b-11eb-9e0e-d121ab81cbc2.png)

1. In your GitHub account, open the [Applications page](https://github.com/settings/installations) and uninstall or revoke all Codacy-related items under the tabs **Installed GitHub Apps** and **Authorized GitHub Apps**. Since you say that you haven't used Codacy for a long time, you may also check under the tab **Authorized OAuth Apps** and revoke any Codacy authorization there.

    ![image](https://user-images.githubusercontent.com/60105800/109158940-ee690c80-776b-11eb-94b2-a0497a243ae7.png)

1. Now, log back into Codacy and authorize the request from Codacy:

    ![image](https://user-images.githubusercontent.com/60105800/109159705-d5ad2680-776c-11eb-94e4-bb52d3293ef5.png)


1. Finally, on the repositories list click **Missing some repositories?** and **Codacy has access to them**.

    ![image](https://user-images.githubusercontent.com/60105800/109160093-448a7f80-776d-11eb-935d-6f0442476af6.png)

    You need to authorize Codacy to have access to your repositories (you can choose to allow all repositories or only some of them):
    
    ![image](https://user-images.githubusercontent.com/60105800/109160224-6d127980-776d-11eb-9a1c-6d08715f3e57.png)

After this last step is complete, you should now be able to navigate to your repository **Settings** page and configure the branches that Codacy analyzes.

![image](https://user-images.githubusercontent.com/60105800/109160410-aba83400-776d-11eb-9b34-23cd47395b13.png)

Please let us know if trying out these steps fixed the issue.

**Comment by bernd-wechner** [comment]
Thank you so much for the detailed response. Unexpected and very very much appreciated. 

Good news and bad news. Good news first, I no have access to branches. Yay, and I set Develop as the main one and wills ee if I get wonderful feedback on pushed commits from here on in. 

Bad news, it didn't go quite like the procedure described, in fact I did all of what you suggested and then could not see the branches still. But then I poked around, logged out, and in and poked around some more and I don't know how, but I found it ;-). Alas I was just poking around scratching my head until I stumbled upon it. My gut feel: this was operator error (i.e. my fault) as in the gist of basically revoking all permissions and recreating them certainly got us there!

From which I can conclude, I think, that Codacy has improved some since I connected to it, and my old authorizations had some legacy settings we just flushed. 

Thanks enormously!

**Comment by pauloribeiro-codacy** [comment]
Yes, Codacy [changed the way it connects to GitHub](https://docs.codacy.com/release-notes/cloud/codacy-now-supports-github-apps/) last year, and it's probably what caused the issue.

Thank you for the feedback @bernd-wechner and I'm glad you can now use Codacy in a way that suits your development process. :+1:
