### ISSUE TITLE
[DOCS-263] Issue for adding a repository failed

### ISSUE THREAD

**Issue by HaojunRen** [codacy/docs#734]
I don't how to contact with you, so I report the issue here:

When I add a repository, it will be blocked in `Detecting languages` for serveral hours, now it is still failed. Refer to the following picture. Would you please tell me how I can do?

![图片](https://user-images.githubusercontent.com/42354711/124356000-76917e00-dc46-11eb-9e12-d2036898bbc7.png)

**Comment by prcr** [comment]
Hello @HaojunRen,

This was most probably a temporary issue caused by a [scheduled maintenance operation](https://docs.codacy.com/release-notes/cloud/scheduled-db-maintenance/) that happened this past Saturday.

Could you please try adding your repositories again so that Codacy can finish analyzing them?

**Comment by HaojunRen** [comment]
Yeah, it goes back to fine
